name: otakudev
version: 0.1.0
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.4.3 <4.0.0'

dependencies: 
  get: 4.6.6
  dio: ^5.5.0+1
  html: ^0.15.4
  lottie: ^3.1.2
  shimmer: ^3.0.0
  url_launcher: ^6.3.0
  flutter_screenutil: ^5.9.3
  cached_network_image: ^3.4.0
  font_awesome_flutter: ^10.4.0
  flutter_widget_from_html: ^0.15.1
  infinite_scroll_pagination: ^4.0.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^3.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets:
    - assets/lotties/
  uses-material-design: true

